# Python - Time Series Learning  
Jaka Eka Sembodo (09/10/2020)

### 01. Installing app

 1. Install Python 3
 2. Install Anaconda
 3. Install jupyter notebook

### 02. Installing Enviroment

First, in this course, we must use pythone enviroment (lot ot libaries) provided from the mentor, it's name 'tsa_course_env.yml', or you can download it from this repo.

* conda env -f tsa_course_env.yml --> for creating the envi
* conda activate tsa_course --> for activating the envi
* conda deactivate --> for deactivating the envi


### 03. Git Repoitory

It this course, I integrated my learning (in this jupyter) to git. Heres the link: https://github.com/jakaesembodo/Python-Time-Series

* git init -> make current directory as git reporsitory
* git clone [URL] -> clone gir directory from URL
* git remote [ALIAS] [URL] -> add remote git url
* git add [FILE NAME] -> add file for pushing
* git commit -m [COMMENT] -> add commit
* git push [ALIAS] -> exec for pushing to repo
* git pull -> pull the newest update from repo
* git log -> show commit history
* git reset --hard -> for reset all commit 

### 04. NumPy

* Numpy = pyhton libary for array and matrix
* we learn about how to make: array, matrix, shape, random number, indexing

In [2]:
import numpy as np
mylist = [1,2,3] #create list with []

In [3]:
type(mylist) #check the type of variable

list

In [5]:
arr = np.array(mylist) #create array variable from existing list
arr

array([1, 2, 3])

In [6]:
type (arr)

numpy.ndarray

In [12]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9]] #create list for matrix
mymatrix = np.array(mylist2) #create matrix 2 dimensional
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#operate matrix with 'matrix_name'. (use dot) + TAB 
mymatrix.shape

(3, 3)

In [15]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(2,20,4) #create list with arange value, start from 2 to 20, add by 4

array([ 2,  6, 10, 14, 18])

In [22]:
np.zeros(10) #create list with zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((10,2))#create list zero as matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
#create a custom matrix value
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
np.ones((5,2))+5

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [36]:
#a bunch of value between value
np.linspace(0,10,13) #show value between 0 - 10, only 13 value (space number)value
##len(np.linspace(0,10,13)) #number of value

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        ])

In [41]:
#make random value 
np.random.randn(5) #for array
np.random.randn(5,5) #for matrix

array([[-3.39660639,  1.09906735, -0.13570041, -0.31934674, -0.76143343],
       [ 0.17128903, -0.55041116, -0.34518275,  0.40767182,  0.58693868],
       [ 0.16667154, -0.41243138,  1.78187755, -1.48423781,  0.39353245],
       [ 0.87496942,  0.44317351, -0.03523784,  0.36841111,  0.02765731],
       [-0.32730495, -0.57189526, -0.59044979,  1.2204019 , -0.71814679]])

In [45]:
#make random with spesific limit
np.random.randint(1,100,2) #there are 2 value, from 1 to 100

array([22,  2])

In [55]:
np.random.seed(5) #for shuffeling (id random)
array = np.random.rand(10)
array

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [56]:
array

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [64]:
#reshape array to matrix
reshape_array = array.reshape(5,2)
reshape_array

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [70]:
#get max min, and its location
reshape_array.max()
reshape_array.min()
reshape_array.argmin()

9

In [75]:
#indexing
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
#slicing array and monipulating
array_0_5 = array[:5]
array_0_5[:] = 100

In [83]:
array_0_5

array([100, 100, 100, 100, 100])

In [84]:
array

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [88]:
arr_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d = np.array(arr_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
#selecting index from matrix (kolom:baris)
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [99]:
array(>7)

SyntaxError: invalid syntax (<ipython-input-99-c6a7f38dcecd>, line 1)

In [100]:
array > 7

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True])

In [102]:
#select matrix with spesiic value
array[array>7]

array([100, 100, 100, 100, 100,   8,   9,  10])

In [114]:
#operation
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
#sum accross the rows (become colom)
arr_2d.sum(axis=0)

array([12, 15, 18])

In [120]:
#sum accross the coloms (become rows)
arr_2d.sum(axis=1)

array([ 6, 15, 24])

In [121]:
arr_2d.mean()

5.0