# Python - Time Series Learning  
Jaka Eka Sembodo (09/10/2020)

### 01. Installing app

 1. Install Python 3
 2. Install Anaconda
 3. Install jupyter notebook

### 02. Installing Enviroment

First, in this course, we must use pythone enviroment (lot ot libaries) provided from the mentor, it's name 'tsa_course_env.yml', or you can download it from this repo.

* conda env -f tsa_course_env.yml --> for creating the envi
* conda activate tsa_course --> for activating the envi
* conda deactivate --> for deactivating the envi


### 03. Git Repoitory

It this course, I integrated my learning (in this jupyter) to git. Heres the link: https://github.com/jakaesembodo/Python-Time-Series

* git init -> make current directory as git reporsitory
* git clone [URL] -> clone gir directory from URL
* git remote set-url [ALIAS] [URL] -> add remote git url
* git add [FILE NAME] -> add file for pushing
* git commit -m [COMMENT] -> add commit
* git push [ALIAS] -> exec for pushing to repo
* git pull -> pull the newest update from repo
* git log -> show commit history
* git reset --hard -> for reset all commit 

### 04. NumPy

* Numpy = pyhton libary for array and matrix
* we learn about how to make: array, matrix, shape, random number, indexing

In [1]:
import numpy as np
mylist = [1,2,3] #create list with []

In [2]:
type(mylist) #check the type of variable

list

In [3]:
arr = np.array(mylist) #create array variable from existing list
arr

array([1, 2, 3])

In [4]:
type (arr)

numpy.ndarray

In [5]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9]] #create list for matrix
mymatrix = np.array(mylist2) #create matrix 2 dimensional
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#operate matrix with 'matrix_name'. (use dot) + TAB 
mymatrix.shape

(3, 3)

In [7]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(2,20,4) #create list with arange value, start from 2 to 20, add by 4

array([ 2,  6, 10, 14, 18])

In [9]:
np.zeros(10) #create list with zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((10,2))#create list zero as matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
#create a custom matrix value
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.ones((5,2))+5

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [13]:
#a bunch of value between value
np.linspace(0,10,13) #show value between 0 - 10, only 13 value (space number)value
##len(np.linspace(0,10,13)) #number of value

array([ 0.        ,  0.83333333,  1.66666667,  2.5       ,  3.33333333,
        4.16666667,  5.        ,  5.83333333,  6.66666667,  7.5       ,
        8.33333333,  9.16666667, 10.        ])

In [14]:
#make random value 
np.random.randn(5) #for array
np.random.randn(5,5) #for matrix

array([[-1.1279631 ,  0.56290746, -1.44729402, -1.21659819,  1.8285021 ],
       [-0.23485023,  3.42174847,  1.4483479 ,  0.37772298, -2.09525675],
       [-0.83146029,  0.38035523,  1.1437388 ,  0.51073236, -0.49148528],
       [ 0.33059431, -1.33119311, -1.50798052,  0.63254214,  0.17779235],
       [ 0.35935912,  0.19831958,  0.89744522,  0.26911009, -2.11480219]])

In [15]:
#make random with spesific limit
np.random.randint(1,100,2) #there are 2 value, from 1 to 100

array([68,  3])

In [16]:
np.random.seed(5) #for shuffeling (id random)
array = np.random.rand(10)
array

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [17]:
array

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [18]:
#reshape array to matrix
reshape_array = array.reshape(5,2)
reshape_array

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [19]:
#get max min, and its location
reshape_array.max()
reshape_array.min()
reshape_array.argmin()

9

In [20]:
#indexing
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#slicing array and monipulating
array_0_5 = array[:5]
array_0_5[:] = 100

In [22]:
array_0_5

array([100, 100, 100, 100, 100])

In [23]:
array

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [24]:
arr_2d = [[1,2,3],[4,5,6],[7,8,9]]
arr_2d = np.array(arr_2d)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
#selecting index from matrix (kolom:baris)
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [26]:
array > 7

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True])

In [27]:
#select matrix with spesiic value
array[array>7]

array([100, 100, 100, 100, 100,   8,   9,  10])

In [28]:
#operation
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
#sum accross the rows (become colom)
arr_2d.sum(axis=0)

array([12, 15, 18])

In [30]:
#sum accross the coloms (become rows)
arr_2d.sum(axis=1)

array([ 6, 15, 24])

In [31]:
arr_2d.mean()

5.0

### 05. Panda 

* Panda = Panel Data
* Make series, dataframe etc

In [44]:
import pandas as pd

In [57]:
array2 = np.arange(2,20,3)
array2

array([ 2,  5,  8, 11, 14, 17])

In [56]:
labels = ('jakarta','bandung','bali','bangka')
labels_2= ('balikpapan','bandung','papua','bangka')

In [58]:
#make a dictionary
dictionary = {'jakarta':2, 'bandung':5, 'bali':8, 'bangka':11, 'balikpapan':1, 'papua':10}

In [59]:
#create a default series
pd.Series(array2)

0     2
1     5
2     8
3    11
4    14
5    17
dtype: int32

In [60]:
#create a custom series
series_1 = pd.Series(data=array2, index = dictionary) #can use ['a','b','c']
series_1

jakarta        2
bandung        5
bali           8
bangka        11
balikpapan    14
papua         17
dtype: int32

In [62]:
#create another series
series_2 = pd.Series(data=[2,3,4], index = ['bangka','bali','bandung']) #can use ['a','b','c']
series_2

bangka     2
bali       3
bandung    4
dtype: int64

In [65]:
series_1 + series_2 #balikpapan, jakarta, papua = nan, due to there is not appear in series_1
#usefull for search mising value

bali          11.0
balikpapan     NaN
bandung        9.0
bangka        13.0
jakarta        NaN
papua          NaN
dtype: float64

In [70]:
#dataframe, a series with multiple kolom, or a table
#first make a random matrix

from numpy.random import randn

np.random.seed(101)
random_1 = randn(5,4)
random_1

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [75]:
#create a dataframe
df_1 = pd.DataFrame(data=random_1, index = 'A B C D E'.split(), columns='bangka bali jakarta bandung'.split())
df_1

bangka      bali   jakarta   bandung
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [73]:
#trivia: for a simple split char to array => 'A B C D E'.split()
'A B C D E'.split()

['A', 'B', 'C', 'D', 'E']

In [84]:
#choose only one colom / series
list = ['bangka','bali']
df_1[['bangka','bali']]

bangka      bali
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [89]:
#make new colom in existing df
df_1['new_city'] = df_1['bangka'] + df_1['bali']

In [90]:
df_1

bangka      bali   jakarta   bandung       new  new_city
A  2.706850  0.628133  0.907969  0.503826  3.334983  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552  2.169552

In [98]:
#remove colom colom = axis 1, row axis = 0
#inplace = TRUE for permanently delete
df_1.drop('new', axis=1, inplace=True)
df_1

bangka      bali   jakarta   bandung  new_city
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [101]:
#remove rows
df_1.drop('C', axis= 0, inplace=True)
df_1

bangka      bali   jakarta   bandung  new_city
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [112]:
#make a series based on row
df_1.loc[['A','D']]
df_1.iloc[[0,2]]

bangka      bali   jakarta   bandung  new_city
A  2.706850  0.628133  0.907969  0.503826  3.334983
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177

In [113]:
#make a series based on row and colom
df_1.loc[['A','B'],['bandung','bali']]

bandung      bali
A  0.503826  0.628133
B  0.605965 -0.319318

In [114]:
#check rhe location more than >0
df_1>0

bangka   bali  jakarta  bandung  new_city
A    True   True     True     True      True
B    True  False    False     True      True
D    True  False    False     True     False
E    True   True     True     True      True

In [135]:
#select cell wirh spesific value
cond_1 = df_1['bali']>0
cond_2 = df_1['bandung']>0.6

In [137]:
#select with condition based on condition above
#for filtering kolom like SQl
df_1[cond_1 & cond_2]

bangka      bali   jakarta   bandung  new_city
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [142]:
#reset index in DF
df_1.reset_index()

index    bangka      bali   jakarta   bandung  new_city
0     A  2.706850  0.628133  0.907969  0.503826  3.334983
1     B  0.651118 -0.319318 -0.848077  0.605965  0.331800
2     D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
3     E  0.190794  1.978757  2.605967  0.683509  2.169552

In [158]:
#make new index with new data
new_index = ('revenue profit omzet equity'.split())
df_1['type'] = new_index
df_1.drop(df_1.columns[5], axis=1, inplace=True)
df_1

bangka      bali   jakarta   bandung  new_city     type
A  2.706850  0.628133  0.907969  0.503826  3.334983  revenue
B  0.651118 -0.319318 -0.848077  0.605965  0.331800   profit
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177    omzet
E  0.190794  1.978757  2.605967  0.683509  2.169552   equity

In [159]:
#set colom as Index
df_1.set_index('type', inplace=True)
df_1

bangka      bali   jakarta   bandung  new_city
type                                                     
revenue  2.706850  0.628133  0.907969  0.503826  3.334983
profit   0.651118 -0.319318 -0.848077  0.605965  0.331800
omzet    0.188695 -0.758872 -0.933237  0.955057 -0.570177
equity   0.190794  1.978757  2.605967  0.683509  2.169552

In [162]:
#info for df DDL
df_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, revenue to equity
Data columns (total 5 columns):
bangka      4 non-null float64
bali        4 non-null float64
jakarta     4 non-null float64
bandung     4 non-null float64
new_city    4 non-null float64
dtypes: float64(5)
memory usage: 192.0+ bytes


In [165]:
#automatically describe df 
df_1.describe()

bangka      bali   jakarta   bandung  new_city
count  4.000000  4.000000  4.000000  4.000000  4.000000
mean   0.934364  0.382175  0.433156  0.687089  1.316539
std    1.201506  1.211563  1.678804  0.193206  1.763628
min    0.188695 -0.758872 -0.933237  0.503826 -0.570177
25%    0.190270 -0.429207 -0.869367  0.580430  0.106306
50%    0.420956  0.154407  0.029946  0.644737  1.250676
75%    1.165051  0.965789  1.332469  0.751396  2.460909
max    2.706850  1.978757  2.605967  0.955057  3.334983

In [181]:
#count sepsific condition
cond_3 = df_1>0
cond_4 = df_1['bangka']>0
df_1[cond_3]
cond_4

type
revenue    True
profit     True
omzet      True
equity     True
Name: bangka, dtype: bool

In [182]:
#must be a coloum
cond_4.value_counts()

True    4
Name: bangka, dtype: int64

In [186]:
sum(cond_4)

type
revenue    True
profit     True
omzet      True
equity     True
Name: bangka, dtype: bool

In [187]:
len(cond_4)

4

In [189]:
#MISSING VALUE
#first we create a dataframe with missing value
df_2 = pd.DataFrame({'A':[1,2,np.nan],'B':[3,np.nan,np.nan],'C':[8,5,4,]})
df_2

A    B  C
0  1.0  3.0  8
1  2.0  NaN  5
2  NaN  NaN  4

In [194]:
#1.) Remove the missing data
#for auomatic drop row
df_2.dropna()

#for drop rows with minimum 2 non
df_2.dropna(thresh=2)


A    B  C
0  1.0  3.0  8
1  2.0  NaN  5

In [195]:
#for drop columns
df_2.dropna(axis=1)

#for drop rows with minimum 2 non
df_2.dropna(axis=1, thresh=2)

A  C
0  1.0  8
1  2.0  5
2  NaN  4

In [202]:
#2.) fill the missing value with value
df_2.fillna(0) #replace na with 0
df_2.fillna(df_2.mean())

A    B  C
0  1.0  3.0  8
1  2.0  3.0  5
2  1.5  3.0  4

In [205]:
#for spesific value
df_2['A'].fillna(df_2.mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [226]:
#GROUP BY
#first, create a dataframe
df_3 = pd.DataFrame({'Nation':['Indonesia','India','Iraq','Indonesia','India','Iraq'],
                     'Sales':['Amir','Budi','Caca','Doni','Eka','Fitri'],
                    'Profit':[12000,212000,300000,450000,110000,230000]})
df_3

Nation  Sales  Profit
0  Indonesia   Amir   12000
1      India   Budi  212000
2       Iraq   Caca  300000
3  Indonesia   Doni  450000
4      India    Eka  110000
5       Iraq  Fitri  230000

In [213]:
#for describe the data
df_3.groupby('Nation').describe().transpose()

Nation                India     Indonesia           Iraq
Profit count       2.000000       2.00000       2.000000
       mean   161000.000000  231000.00000  265000.000000
       std     72124.891681  309712.77016   49497.474683
       min    110000.000000   12000.00000  230000.000000
       25%    135500.000000  121500.00000  247500.000000
       50%    161000.000000  231000.00000  265000.000000
       75%    186500.000000  340500.00000  282500.000000
       max    212000.000000  450000.00000  300000.000000

In [216]:
df_3.head(n=10)

Nation  Sales  Profit
0  Indonesia   Amir   12000
1      India   Budi  212000
2       Iraq   Caca  300000
3  Indonesia   Doni  450000
4      India    Eka  110000
5       Iraq  Fitri  230000

In [217]:
df_3['Nation'].unique()

array(['Indonesia', 'India', 'Iraq'], dtype=object)

In [218]:
df_3['Nation'].nunique()

3

In [219]:
len(df_3['Nation'])

6

In [220]:
df_3['Nation'].value_counts()

India        2
Iraq         2
Indonesia    2
Name: Nation, dtype: int64

In [231]:
#conditional selection
df_3_filter1 = df_3[ (df_3['Nation']=='India')  &  (df_3['Profit']>150000)]
df_3_filter1

Nation Sales  Profit
1  India  Budi  212000

In [233]:
#create function
def times_three(number):
    return number*3

In [248]:
#add new coloum with function
df_3['Profit x 3'] = df_3['Profit'].apply(times_three)
df_3

Nation  Sales  Profit  Profit x 3
0  Indonesia   Amir   12000       36000
1      India   Budi  212000      636000
2       Iraq   Caca  300000      900000
3  Indonesia   Doni  450000     1350000
4      India    Eka  110000      330000
5       Iraq  Fitri  230000      690000

In [249]:
#for delete columns
del df_3['Profit x 3']

In [257]:
df_3.sort_values('Profit', ascending=False)

Nation  Sales  Profit
3  Indonesia   Doni  450000
2       Iraq   Caca  300000
5       Iraq  Fitri  230000
1      India   Budi  212000
4      India    Eka  110000
0  Indonesia   Amir   12000

In [267]:
#IMPORT DATA
#from CSV first
#important need plac r before path
pd.read_csv(r'example.csv')
df_4 = pd.read_csv(r'example.csv')
df_4

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [270]:
df_4_filter1 = df_4[['a','d']]
df_4_filter1

a   d
0   0   3
1   4   7
2   8  11
3  12  15

In [275]:
#output on a new CSV
df_4_filter1.to_csv('output_1.csv', index=True)

In [279]:
#input from excel
df_5 = pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')
df_5

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [285]:
#input from HTML
df_6 = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/banklist.html')
len(df_6)

1

In [291]:
df_6

[                                             Bank Name                City  \
 0                                 The First State Bank       Barboursville   
 1                                   Ericson State Bank             Ericson   
 2                     City National Bank of New Jersey              Newark   
 3                                        Resolute Bank              Maumee   
 4                                Louisa Community Bank              Louisa   
 5                                 The Enloe State Bank              Cooper   
 6                  Washington Federal Bank for Savings             Chicago   
 7      The Farmers and Merchants State Bank of Argonia             Argonia   
 8                                  Fayette County Bank          Saint Elmo   
 9    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 10                                      First NBC Bank         New Orleans   
 11                                       Proficio B